# Generated by Django 3.2.15 on 2022-09-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_trace_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardhistory',
            name='record_type',
            field=models.CharField(choices=[('PLACED_ON_TILE', 'PLACED_ON_TILE'), ('ATTACK', 'ATTACK'), ('MYSTERY_ACTIVATED', 'MYSTERY_ACTIVATED'), ('SPELL_PLAYED', 'SPELL_PLAYED'), ('DEATH', 'DEATH')], default='PLACED_ON_TILE', max_length=32),
        ),
        migrations.AddField(
            model_name='cardhistory',
            name='turn_number',
            field=models.IntegerField(default=0),
        ),
    ]
